#!/bin/bash
#Created by Fernando Fuentes. v1.0b
#
background () {
  echo $$ > /tmp/check_lenny.pid
  while true;
email="youemaila@here.com"
subj="Subject: Lenny Recording $(date)"
do
    for f in /tmp/Lenny/*.wav
    do
      if [ -f $f ]
      then
        fuser -s $f
        if [ $? -ne 0 ]
        then
	mv -f "${f%\.*}".wav "/tmp/"
       fi
     fi
done 
cd /tmp/
    for i in *.*.wav; do
	if [ -e "$i" ]; then
	file=`basename "$i" .wav`
	echo "$subj \
From: AsteriskPBX
To: $email" | \
mime-pack "New Recording" "$file.wav" "audio/wav" | \
sendmail -t
rm "$file.wav"
	fi
      done

   sleep 30
  done
  rm -f /tmp/check_recording.pid
}

background&
